
repository:
  private: false

  has_issues: true
  has_projects: false
  has_wiki: false

  allow_squash_merge: true
  allow_merge_commit: false
  allow_rebase_merge: false
  delete_branch_on_merge: true

  default_branch: main

branches:
  - name: main
    protection:
      required_pull_request_reviews: null
      required_status_checks: null
      enforce_admins: true
      required_linear_history: true
      restrictions: null
